PREFIX  xsl:  <http://www.w3.org/1999/XSL/Transform>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  score: <http://vivoweb.org/ontology/score#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  core: <http://vivoweb.org/ontology/core#>
PREFIX  ufVivo: <http://vivo.ufl.edu/ontology/vivo-ufl/>

CONSTRUCT 
{
 ?roleuri rdf:type ufVivo:tagForDeletion . 
}
WHERE
{
  graph <http://vitro.mannlib.cornell.edu/default/vitro-kb-2> {
    ?granturi rdf:type core:Grant .
    ?granturi core:relatedRole ?roleuri .
    ?roleuri ufVivo:harvestedBy "DSR-Harvester" .
  }
}
