PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ufVivo: <http://vivo.ufl.edu/ontology/vivo-ufl/>
PREFIX core: <http://vivoweb.org/ontology/core#>

construct 
{
 ?datetimeinturi rdf:type ufVivo:tagForDeletion .
}
WHERE {

 ?granturi rdf:type core:Grant .

 ?granturi core:dateTimeInterval ?datetimeinturi .
 ?granturi ufVivo:harvestedBy "DSR-Harvester" .
}
